### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by zylluck** [Lmy0217/Flight#1]
想请教关于这个携程是不是有反爬机制了？我用你的代码运行出现404，还有那个图形框不能显示。可否答疑一下，谢谢，

**Comment by Lmy0217** [comment]
@zylluck 在这里 [flight.py#L60](https://github.com/Lmy0217/Flight/blob/master/flight.py#L60) 要加入自己的 Cookie。

**Comment by zylluck** [comment]
有点小白，我复制网址打开，他显示也是404，不是网址失效了吗，

**Comment by Lmy0217** [comment]
@zylluck 那应该是换了

**Comment by Lmy0217** [comment]
@zylluck 可能改成这个 https://flights.ctrip.com/itinerary/api/12808/products 了？

**Comment by zylluck** [comment]
对，我试过这个，但是他好像只能爬取一条航班线的，所以是不是现在爬取携程只能单条，没有fis那个列表了吗

**Comment by Lmy0217** [comment]
@zylluck 有多个班次的啊

**Comment by zylluck** [comment]
https://flights.ctrip.com/itinerary/api/12808/products ，我用这个链接爬取，他提示我fis找不到，是不是开发工具那里Preview那里没有fis信息的原因呢，也没有r，rk,ck字段，我是不是直接把他们删掉就行了呀？

**Comment by Lmy0217** [comment]
@zylluck 字段换了，要按照返回的修改

**Comment by zylluck** [comment]
没有对应的值是把他删掉吗？前后两个网址相差也太大了

**Comment by Lmy0217** [comment]
需要什么就保留什么

**Comment by zylluck** [comment]
就是，不好意思，你有空可以麻烦帮忙看一下吗，修改一下吗，我修改了大半个月一点进展都没有，真的太难了。

**Comment by Lmy0217** [comment]
@zylluck 我最近也比较忙，不好意思啊

**Comment by zylluck** [comment]
没事没事，麻烦你了哈 辛苦了

**Comment by zylluck** [comment]
想问一下，你的预测算法是时间序列算法吗

**Comment by Lmy0217** [comment]
LSTM

**Comment by zylluck** [comment]
你好，再问一个问题嘿嘿，就是我因为想把你的改成python3，把你画布里面的show（）方法改成draw（）这样对吗，

**Comment by Lmy0217** [comment]
我的就是python3
